version: 7
profiles:
  - type: ssh
    name: RackNerd
    options:
      host: 104.168.125.16
      algorithms: {}
      input: {}
      user: kaiser
      auth: password
    weight: -1
    id: ssh:custom:LSA-VM-1:a6701984-bb4b-4f46-add9-a201c3b3e7dc
    icon: fab fa-linux
    color: '#ffd500'
    terminalColorScheme:
      name: FirefoxDev
      foreground: '#7c8fa4'
      background: '#0e1011'
      cursor: '#708284'
      colors:
        - '#002831'
        - '#e63853'
        - '#5eb83c'
        - '#a57706'
        - '#359ddf'
        - '#d75cff'
        - '#4b73a2'
        - '#dcdcdc'
        - '#001e27'
        - '#e1003f'
        - '#1d9000'
        - '#cd9409'
        - '#006fc0'
        - '#a200da'
        - '#005794'
        - '#e2e2e2'
hotkeys:
  toggle-window:
    - Ctrl-Space
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
    - Shift-Insert
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-window:
    - Ctrl-Shift-N
  new-tab:
    - Ctrl-Shift-T
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-T
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  duplicate-tab: []
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-E
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-maximize:
    - Ctrl-Alt-Enter
  close-pane: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-T
  delete-line:
    - Ctrl-Shift-Backspace
  scroll-to-bottom: []
  settings-tab: {}
  explode-tab:
    - Ctrl-Shift-.
  combine-tabs:
    - Ctrl-Shift-,
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  focus-all-tabs:
    - Ctrl-Alt-Shift-I
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - Alt-PageUp
  scroll-down:
    - Alt-PageDown
  restart-tab: []
  command-selector:
    - Ctrl-Shift-P
  reconnect-tab: []
  disconnect-tab: []
terminal:
  searchOptions: {}
  colorScheme:
    name: Argonaut
    foreground: '#fffaf4'
    background: '#0e1019'
    cursor: '#ff0018'
    colors:
      - '#232323'
      - '#ff000f'
      - '#8ce10b'
      - '#ffb900'
      - '#008df8'
      - '#6d43a6'
      - '#00d8eb'
      - '#ffffff'
      - '#444444'
      - '#ff2740'
      - '#abe15b'
      - '#ffd242'
      - '#0092ff'
      - '#9a5feb'
      - '#67fff0'
      - '#ffffff'
  customColorSchemes: []
  background: colorScheme
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
ssh:
  knownHosts:
    - host: 192.168.0.110
      port: 22
      type: ecdsa-sha2-nistp256
      digest: tyriRhbdyUyNLQowy4CuPS8ZduJ/2++06jBf+kFA0tE=
    - host: localhost
      port: 10001
      type: ecdsa-sha2-nistp256
      digest: gPpToT/TA+aGxQM9I/PhQNkZc1p7VAz3cMBQFt87Eck=
    - host: 104.168.125.16
      port: 22
      type: ecdsa-sha2-nistp256
      digest: PjMboBgq/FLz0/uiJBYhoKKAX+5SyM5xnuynGRaFiOo=
configSync:
  parts: {}
  token: >-
    ac7cf066eb7e322e566066930a20046c5722258d4d848b16f12f67e92e9d5fd180d6ab3d28bfd7b0409d1548c05e969b84f590ba68a3904150da53ecd71c7f80
  configID: 11117
clickableLinks: {}
appearance:
  theme: Standard (legacy)
  vibrancy: true
hacks: {}
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults: {}
accessibility: {}
providerBlacklist: []
commandBlacklist: []
groups: []
profileBlacklist: []
